---
- apt: name={{ item }} state=latest
  with_items:
    - rabbitmq-server
- service: name=rabbitmq-server state=started enabled=yes
- rabbitmq_plugin: names=rabbitmq_management state=enabled
- service: name=rabbitmq-server state=restarted
