- hosts: all
  sudo: True

  tasks:
  - apt: update-cache=yes upgrade=yes

  - include: tasks/database.yaml tags=database
  - include: tasks/messaging.yaml tags=messaging
  - include: tasks/webinterface.yaml tags=webinterface

  - apt: name={{ item }} state=latest
    with_items:
      - git
      - libmysqlclient-dev
      - python-dev
      - python-virtualenv
    tags:
      - api
      - producer
      - tracker
      - worker

  - command: pip install -r /vagrant/requirements.txt
    tags:
      - api
      - producer
      - tracker
      - worker

  - command: python setup.py install
    args:
      chdir: /vagrant
    tags:
      - api
      - producer
      - tracker
      - worker

  - copy: src=files/run_api.sh dest=/home/vagrant/run_api.sh mode=0755
    tags: api
  - copy: src=files/run_producer.sh dest=/home/vagrant/run_producer.sh mode=0755
    tags: producer
  - copy: src=files/run_tracker.sh dest=/home/vagrant/run_tracker.sh mode=0755
    tags: tracker
  - copy: src=files/run_worker.sh dest=/home/vagrant/run_worker.sh mode=0755
    tags: worker
