- hosts: all
  sudo: True

  tasks:
  - apt: update-cache=yes upgrade=yes
  - include: tasks/api.yaml tags=api
  - include: tasks/database.yaml tags=database
  - include: tasks/messaging.yaml tags=messaging
  - include: tasks/webinterface.yaml tags=webinterface

  - apt: name={{ item }} state=latest
    with_items:
      - git
      - libmysqlclient-dev
      - python-daemon
      - python-dev
      - python-kombu
      - python-pbr
      - python-pillow
      - python-requests
      - python-virtualenv
    tags:
      - worker
      - producer
      - tracker
      - api

  - command: python setup.py install
    args:
      chdir: /vagrant
    tags:
      - worker
      - producer
      - tracker
      - api

  - copy: src=files/run_worker.sh dest=/home/vagrant/run_worker.sh mode=0755
    tags: worker
  - copy: src=files/run_tracker.sh dest=/home/vagrant/run_tracker.sh mode=0755
    tags: tracker
  - copy: src=files/run_producer.sh dest=/home/vagrant/run_producer.sh mode=0755
    tags: producer
  - copy: src=files/run_api.sh dest=/home/vagrant/run_api.sh mode=0755
    tags: api
