- hosts: all
  sudo: True

  tasks:
  - apt: update-cache=yes upgrade=yes
  - include: tasks/database.yaml tags=database
  - include: tasks/messaging.yaml tags=messaging

  - apt: name={{ item }} state=latest
    with_items:
      - git
      - libmysqlclient-dev
      - python-daemon
      - python-dev
      - python-kombu
      - python-pillow
      - python-sqlalchemy
      - python-virtualenv
      - python-pbr
    tags:
      - worker
      - producer
      - tracker

  - command: python setup.py install
    args:
      chdir: /vagrant
    tags:
      - worker
      - producer
      - tracker

  - copy: src=files/run_worker.sh dest=/home/vagrant/run_worker.sh mode=0755
    tags: worker
  - copy: src=files/run_tracker.sh dest=/home/vagrant/run_tracker.sh mode=0755
    tags: tracker
  - copy: src=files/run_producer.sh dest=/home/vagrant/run_producer.sh mode=0755
    tags: producer
