- hosts: all
  sudo: True

  tasks:
  - apt: update-cache=yes upgrade=yes
  - command: /vagrant/contrib/install.sh -i faafo -i messaging -i database -r api -r worker -r demo -d 'mysql://faafo:password@localhost:3306/faafo' -m 'amqp://guest:guest@localhost:5672/' -e 'http://localhost'
